services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
        - ./data/db:/data/db
        - ./data/configdb:/data/configdb

  haskell:
    image: haskell:9.4.7
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "stack install && stack build && stack exec Main-exe"
    depends_on:
      - mongo
