name:                DotaHaskellAnalytics
version:             0.1.0.0
github:              "githubuser/DotaHaskellAnalytics"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DotaHaskellAnalytics#readme>

dependencies:
- base >= 4.7 && < 5
- req
- aeson
- text
- mongoDB
- network
- containers
- async
- rate-limit
- time-units
- Chart
- Chart-diagrams
- lens
- mtl
- data-default-class
- colour

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Query-exe:
    main:                Main.hs
    source-dirs:         run-query
    
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DotaHaskellAnalytics

  Data-exe:
    main:                Main.hs
    source-dirs:         run-data
    
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DotaHaskellAnalytics

    Main-exe:
      main:                Main.hs
      source-dirs:         run
      
      ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      dependencies:
      - DotaHaskellAnalytics

tests:
  DotaHaskellAnalytics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DotaHaskellAnalytics
    - hspec
